apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-application
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-application
  template:
    metadata:
      labels:
        app: hello-application
    spec:
      containers:
      - name: hello-application
        image: ikbelkhemiri/helloapplicatio:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-application
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

